package pe.edu.upeu.CONEIA.entity;
// Generated 30-ene-2018 10:51:27 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleInscripcion generated by hbm2java
 */
@Entity
@Table(name = "detalle_inscripcion", catalog = "appconeia_db")
@NamedQueries({
@NamedQuery(name="Inscritos", query="FROM DetalleInscripcion d where d.iddetalleInscripcion  = :iddetalleInscripcion"),
@NamedQuery(name="InscripcionPersona", query="FROM DetalleInscripcion d where d.persona = :persona")})
public class DetalleInscripcion implements java.io.Serializable {

	private Integer iddetalleInscripcion;
	private Inscripcion inscripcion;
	private Persona persona;
	private String estado;
	private Integer importe;
	private Set<InscripcionTaller> inscripcionTallers = new HashSet<InscripcionTaller>(0);

	public DetalleInscripcion() {
	}

	public DetalleInscripcion(Inscripcion inscripcion, Persona persona) {
		this.inscripcion = inscripcion;
		this.persona = persona;
	}

	public DetalleInscripcion(Inscripcion inscripcion, Persona persona, String estado, Integer importe,
			Set<InscripcionTaller> inscripcionTallers) {
		this.inscripcion = inscripcion;
		this.persona = persona;
		this.estado = estado;
		this.importe = importe;
		this.inscripcionTallers = inscripcionTallers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddetalle_inscripcion", unique = true, nullable = false)
	public Integer getIddetalleInscripcion() {
		return this.iddetalleInscripcion;
	}

	public void setIddetalleInscripcion(Integer iddetalleInscripcion) {
		this.iddetalleInscripcion = iddetalleInscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idinscripcion", nullable = false)
	public Inscripcion getInscripcion() {
		return this.inscripcion;
	}

	public void setInscripcion(Inscripcion inscripcion) {
		this.inscripcion = inscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "importe")
	public Integer getImporte() {
		return this.importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detalleInscripcion")
//	@OneToMany(fetch = FetchType.JOIN, mappedBy = "detalleInscripcion")
	public Set<InscripcionTaller> getInscripcionTallers() {
		return this.inscripcionTallers;
	}

	public void setInscripcionTallers(Set<InscripcionTaller> inscripcionTallers) {
		this.inscripcionTallers = inscripcionTallers;
	}

}
