package pe.edu.upeu.CONEIA.entity;
// Generated 30-ene-2018 10:51:27 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InscripcionTaller generated by hbm2java
 */
@Entity
@Table(name = "inscripcion_taller", catalog = "appconeia_db")
@NamedQueries({
@NamedQuery(name="InscripcionTaller", query="FROM InscripcionTaller i where i.detalleInscripcion =:detalleInscripcion")})
public class InscripcionTaller implements java.io.Serializable {

	private Integer idinscripcionTaller;
	private DetalleInscripcion detalleInscripcion;
	private Taller taller;
	private Date fecha;
	private Integer asistencia;
	private Integer estado;
	private Date hora;

	public InscripcionTaller() {
	}

	public InscripcionTaller(DetalleInscripcion detalleInscripcion, Taller taller) {
		this.detalleInscripcion = detalleInscripcion;
		this.taller = taller;
	}

	public InscripcionTaller(DetalleInscripcion detalleInscripcion, Taller taller, Date fecha, Integer asistencia,
			Integer estado, Date hora) {
		this.detalleInscripcion = detalleInscripcion;
		this.taller = taller;
		this.fecha = fecha;
		this.asistencia = asistencia;
		this.estado = estado;
		this.hora = hora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idinscripcion_taller", unique = true, nullable = false)
	public Integer getIdinscripcionTaller() {
		return this.idinscripcionTaller;
	}

	public void setIdinscripcionTaller(Integer idinscripcionTaller) {
		this.idinscripcionTaller = idinscripcionTaller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddetalle_inscripcion", nullable = false)
	public DetalleInscripcion getDetalleInscripcion() {
		return this.detalleInscripcion;
	}

	public void setDetalleInscripcion(DetalleInscripcion detalleInscripcion) {
		this.detalleInscripcion = detalleInscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtaller", nullable = false)
	public Taller getTaller() {
		return this.taller;
	}

	public void setTaller(Taller taller) {
		this.taller = taller;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "asistencia")
	public Integer getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Integer asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

}
