package pe.edu.upeu.CONEIA.entity;
// Generated 20-dic-2017 19:51:48 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleInscripcion generated by hbm2java
 */
@Entity
@Table(name = "detalle_inscripcion", catalog = "dbconeia")
public class DetalleInscripcion implements java.io.Serializable {

	private Integer iddetalleInscripcion;
	private Inscripcion inscripcion;
	private Taller taller;
	private Date fecha;
	private Integer asistencia;
	private Integer estado;
	private Date hora;

	public DetalleInscripcion() {
	}

	public DetalleInscripcion(Inscripcion inscripcion, Taller taller) {
		this.inscripcion = inscripcion;
		this.taller = taller;
	}

	public DetalleInscripcion(Inscripcion inscripcion, Taller taller, Date fecha, Integer asistencia, Integer estado,
			Date hora) {
		this.inscripcion = inscripcion;
		this.taller = taller;
		this.fecha = fecha;
		this.asistencia = asistencia;
		this.estado = estado;
		this.hora = hora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddetalle_inscripcion", unique = true, nullable = false)
	public Integer getIddetalleInscripcion() {
		return this.iddetalleInscripcion;
	}

	public void setIddetalleInscripcion(Integer iddetalleInscripcion) {
		this.iddetalleInscripcion = iddetalleInscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idinscripcion", nullable = false)
	public Inscripcion getInscripcion() {
		return this.inscripcion;
	}

	public void setInscripcion(Inscripcion inscripcion) {
		this.inscripcion = inscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtaller", nullable = false)
	public Taller getTaller() {
		return this.taller;
	}

	public void setTaller(Taller taller) {
		this.taller = taller;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "asistencia")
	public Integer getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Integer asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

}
