package pe.edu.upeu.CONEIA.entity;
// Generated 03-ene-2018 11:40:37 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePrivilegio generated by hbm2java
 */
@Entity
@Table(name = "detalle_privilegio", catalog = "dbconeia")
public class DetallePrivilegio implements java.io.Serializable {

	private Integer iddetallePrivilegio;
	private Privilegio privilegio;
	private Rol rol;
	private Integer estado;

	public DetallePrivilegio() {
	}

	public DetallePrivilegio(Privilegio privilegio, Rol rol) {
		this.privilegio = privilegio;
		this.rol = rol;
	}

	public DetallePrivilegio(Privilegio privilegio, Rol rol, Integer estado) {
		this.privilegio = privilegio;
		this.rol = rol;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddetalle_privilegio", unique = true, nullable = false)
	public Integer getIddetallePrivilegio() {
		return this.iddetallePrivilegio;
	}

	public void setIddetallePrivilegio(Integer iddetallePrivilegio) {
		this.iddetallePrivilegio = iddetallePrivilegio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprivilegio", nullable = false)
	public Privilegio getPrivilegio() {
		return this.privilegio;
	}

	public void setPrivilegio(Privilegio privilegio) {
		this.privilegio = privilegio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
