package pe.edu.upeu.CONEIA.entity;
// Generated 03-ene-2018 11:40:37 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name = "inscripcion", catalog = "dbconeia")
public class Inscripcion implements java.io.Serializable {

	private Integer idinscripcion;
	private Date fecha;
	private String voucher;
	private Integer estado;
	private Set<DetalleInscripcion> detalleInscripcions = new HashSet<DetalleInscripcion>(0);

	public Inscripcion() {
	}

	public Inscripcion(Date fecha, String voucher, Integer estado, Set<DetalleInscripcion> detalleInscripcions) {
		this.fecha = fecha;
		this.voucher = voucher;
		this.estado = estado;
		this.detalleInscripcions = detalleInscripcions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idinscripcion", unique = true, nullable = false)
	public Integer getIdinscripcion() {
		return this.idinscripcion;
	}

	public void setIdinscripcion(Integer idinscripcion) {
		this.idinscripcion = idinscripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "voucher", length = 45)
	public String getVoucher() {
		return this.voucher;
	}

	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inscripcion")
	public Set<DetalleInscripcion> getDetalleInscripcions() {
		return this.detalleInscripcions;
	}

	public void setDetalleInscripcions(Set<DetalleInscripcion> detalleInscripcions) {
		this.detalleInscripcions = detalleInscripcions;
	}

}
