package pe.edu.upeu.CONEIA.entity;
// Generated 03-ene-2018 11:40:37 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InscripcionTaller generated by hbm2java
 */
@Entity
@Table(name = "inscripcion_taller", catalog = "dbconeia")
@NamedQueries({
@NamedQuery(name="InscripcionTaller", query="FROM InscripcionTaller i where i.detalleInscripcion =:detalleInscripcion and i.hora  = :hora and i.fecha =:fecha")})
public class InscripcionTaller implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idinscripcionTaller;
	private DetalleInscripcion detalleInscripcion;
	private Taller taller;
	private Date fecha;
	private Integer asistencia;
	private Integer estado;
	private Date hora;
	private Date fecha_inscripcion;

	public InscripcionTaller() {
	}

	public InscripcionTaller(int idinscripcionTaller, DetalleInscripcion detalleInscripcion, Taller taller) {
		this.idinscripcionTaller = idinscripcionTaller;
		this.detalleInscripcion = detalleInscripcion;
		this.taller = taller;
	}

	public InscripcionTaller(int idinscripcionTaller, DetalleInscripcion detalleInscripcion, Taller taller, Date fecha,
			Integer asistencia, Integer estado, Date hora, Date fecha_inscripcion) {
		this.idinscripcionTaller = idinscripcionTaller;
		this.detalleInscripcion = detalleInscripcion;
		this.taller = taller;
		this.fecha = fecha;
		this.asistencia = asistencia;
		this.estado = estado;
		this.hora = hora;
		this.fecha_inscripcion = fecha_inscripcion;
	}

	@Id

	@Column(name = "idinscripcion_taller", unique = true, nullable = false)
	public int getIdinscripcionTaller() {
		return this.idinscripcionTaller;
	}

	public void setIdinscripcionTaller(int idinscripcionTaller) {
		this.idinscripcionTaller = idinscripcionTaller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddetalle_inscripcion", nullable = false)
	public DetalleInscripcion getDetalleInscripcion() {
		return this.detalleInscripcion;
	}

	public void setDetalleInscripcion(DetalleInscripcion detalleInscripcion) {
		this.detalleInscripcion = detalleInscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtaller", nullable = false)
	public Taller getTaller() {
		return this.taller;
	}

	public void setTaller(Taller taller) {
		this.taller = taller;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}
	
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inscripcion", length = 10)
	public Date getFecha_inscripcion() {
		return this.fecha_inscripcion;
	}

	public void setFecha_inscripcion(Date fecha_inscripcion) {
		this.fecha_inscripcion = fecha_inscripcion;
	}
	
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "asistencia")
	public Integer getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Integer asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

}
