package pe.edu.upeu.CONEIA.entity;
// Generated 25-ene-2018 18:55:26 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name = "inscripcion", catalog = "dbconeia")
public class Inscripcion implements java.io.Serializable {

	private Integer idinscripcion;
	private Date fecha;
	private String nroVoucher;
	private String urlVoucher;
	private Integer estado;
	private Date fechaUpdate;
	private Set<DetalleInscripcion> detalleInscripcions = new HashSet<DetalleInscripcion>(0);

	public Inscripcion() {
	}

	public Inscripcion(Date fecha, String nroVoucher, String urlVoucher, Integer estado, Date fechaUpdate,
			Set<DetalleInscripcion> detalleInscripcions) {
		this.fecha = fecha;
		this.nroVoucher = nroVoucher;
		this.urlVoucher = urlVoucher;
		this.estado = estado;
		this.fechaUpdate = fechaUpdate;
		this.detalleInscripcions = detalleInscripcions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idinscripcion", unique = true, nullable = false)
	public Integer getIdinscripcion() {
		return this.idinscripcion;
	}

	public void setIdinscripcion(Integer idinscripcion) {
		this.idinscripcion = idinscripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "nro_voucher", length = 45)
	public String getNroVoucher() {
		return this.nroVoucher;
	}

	public void setNroVoucher(String nroVoucher) {
		this.nroVoucher = nroVoucher;
	}

	@Column(name = "url_voucher", length = 45)
	public String getUrlVoucher() {
		return this.urlVoucher;
	}

	public void setUrlVoucher(String urlVoucher) {
		this.urlVoucher = urlVoucher;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_update", length = 10)
	public Date getFechaUpdate() {
		return this.fechaUpdate;
	}

	public void setFechaUpdate(Date fechaUpdate) {
		this.fechaUpdate = fechaUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inscripcion")
	public Set<DetalleInscripcion> getDetalleInscripcions() {
		return this.detalleInscripcions;
	}

	public void setDetalleInscripcions(Set<DetalleInscripcion> detalleInscripcions) {
		this.detalleInscripcions = detalleInscripcions;
	}

}
