package pe.edu.upeu.CONEIA.entity;
// Generated 20-dic-2017 19:51:48 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name = "inscripcion", catalog = "dbconeia", uniqueConstraints = @UniqueConstraint(columnNames = "idpersona"))
public class Inscripcion implements java.io.Serializable {

	private Integer idinscripcion;
	private Persona persona;
	private Date fecha;
	private String voucher;
	private String deporte;
	private Integer estado;
	private Set<DetalleInscripcion> detalleInscripcions = new HashSet<DetalleInscripcion>(0);

	public Inscripcion() {
	}

	public Inscripcion(Persona persona) {
		this.persona = persona;
	}

	public Inscripcion(Persona persona, Date fecha, String voucher, String deporte, Integer estado,
			Set<DetalleInscripcion> detalleInscripcions) {
		this.persona = persona;
		this.fecha = fecha;
		this.voucher = voucher;
		this.deporte = deporte;
		this.estado = estado;
		this.detalleInscripcions = detalleInscripcions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idinscripcion", unique = true, nullable = false)
	public Integer getIdinscripcion() {
		return this.idinscripcion;
	}

	public void setIdinscripcion(Integer idinscripcion) {
		this.idinscripcion = idinscripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "voucher", length = 45)
	public String getVoucher() {
		return this.voucher;
	}

	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

	@Column(name = "deporte", length = 45)
	public String getDeporte() {
		return this.deporte;
	}

	public void setDeporte(String deporte) {
		this.deporte = deporte;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inscripcion")
	public Set<DetalleInscripcion> getDetalleInscripcions() {
		return this.detalleInscripcions;
	}

	public void setDetalleInscripcions(Set<DetalleInscripcion> detalleInscripcions) {
		this.detalleInscripcions = detalleInscripcions;
	}

}
