package pe.edu.upeu.CONEIA.entity;
// Generated 03-ene-2018 11:40:37 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name = "taller", catalog = "dbconeia")
@NamedQueries({
@NamedQuery(name="Talleres", query="FROM Taller t where t.horaInicio  = :horaInicio and t.fecha=:fecha"),
@NamedQuery(name="Stock", query="FROM Taller t where t.idtaller  = :idtaller")})
public class Taller implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtaller;
	private Tipo tipo;
	private String nombre;
	private String ponente;
	private Date horaInicio;
	private Date horaFin;
	private Date fecha;
	private String descripcion;
	private Integer nroVacantes;
	private Set<InscripcionTaller> inscripcionTallers = new HashSet<InscripcionTaller>(0);

	public Taller() {
	}

	public Taller(Tipo tipo) {
		this.tipo = tipo;
	}

	public Taller(Tipo tipo, String nombre, String ponente, Date horaInicio, Date horaFin, Date fecha,
			String descripcion, Integer nroVacantes, Set<InscripcionTaller> inscripcionTallers) {
		this.tipo = tipo;
		this.nombre = nombre;
		this.ponente = ponente;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.nroVacantes = nroVacantes;
		this.inscripcionTallers = inscripcionTallers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtaller", unique = true, nullable = false)
	public Integer getIdtaller() {
		return this.idtaller;
	}

	public void setIdtaller(Integer idtaller) {
		this.idtaller = idtaller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipo", nullable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ponente", length = 45)
	public String getPonente() {
		return this.ponente;
	}

	public void setPonente(String ponente) {
		this.ponente = ponente;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nro_vacantes")
	public Integer getNroVacantes() {
		return this.nroVacantes;
	}

	public void setNroVacantes(Integer nroVacantes) {
		this.nroVacantes = nroVacantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
	public Set<InscripcionTaller> getInscripcionTallers() {
		return this.inscripcionTallers;
	}

	public void setInscripcionTallers(Set<InscripcionTaller> inscripcionTallers) {
		this.inscripcionTallers = inscripcionTallers;
	}

}
