package pe.edu.upeu.CONEIA.entity;
// Generated 25-ene-2018 18:55:26 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VistaDetalleInscripcion generated by hbm2java
 */
@Entity
@Table(name = "vista_detalle_inscripcion", catalog = "dbconeia")
public class VistaDetalleInscripcion implements java.io.Serializable {

	private VistaDetalleInscripcionId id;

	public VistaDetalleInscripcion() {
	}

	public VistaDetalleInscripcion(VistaDetalleInscripcionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idinscripcion", column = @Column(name = "idinscripcion", nullable = false)),
			@AttributeOverride(name = "cuenta", column = @Column(name = "cuenta", nullable = false)) })
	public VistaDetalleInscripcionId getId() {
		return this.id;
	}

	public void setId(VistaDetalleInscripcionId id) {
		this.id = id;
	}

}
