package pe.edu.upeu.CONEIA.entity;
// Generated 25-ene-2018 18:55:26 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VistaDetalleInscripcionId generated by hbm2java
 */
@Embeddable
public class VistaDetalleInscripcionId implements java.io.Serializable {

	private int idinscripcion;
	private long cuenta;

	public VistaDetalleInscripcionId() {
	}

	public VistaDetalleInscripcionId(int idinscripcion, long cuenta) {
		this.idinscripcion = idinscripcion;
		this.cuenta = cuenta;
	}

	@Column(name = "idinscripcion", nullable = false)
	public int getIdinscripcion() {
		return this.idinscripcion;
	}

	public void setIdinscripcion(int idinscripcion) {
		this.idinscripcion = idinscripcion;
	}

	@Column(name = "cuenta", nullable = false)
	public long getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(long cuenta) {
		this.cuenta = cuenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaDetalleInscripcionId))
			return false;
		VistaDetalleInscripcionId castOther = (VistaDetalleInscripcionId) other;

		return (this.getIdinscripcion() == castOther.getIdinscripcion()) && (this.getCuenta() == castOther.getCuenta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdinscripcion();
		result = 37 * result + (int) this.getCuenta();
		return result;
	}

}
